version: 0.1

phases:
  install:
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "Installing dependencies - `pwd`"
      - cd app && npm install
      - echo "dependencies install completed `date`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - echo "Building SAM template"
      - aws cloudformation package --template-file sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file output_sam.yaml
      - echo "Building warsql tool"
      - cd warsql
      - cmake .
      - make
      - #TODO deploy warsql on instance
  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - output_sam.yaml
  discard-paths: yes
