version: 0.1

phases:
  install:
    commands:
      - echo "No install commands"
  pre_build:
    commands:
      - echo "Installing dependencies"
      - cd app && npm install
  build:
    commands:
      - echo "Copying tools"
      - aws s3 cp db/schema.sql s3://$TOOLS_BUCKET
      - aws s3 cp import/warsql-ec2-optimized s3://$TOOLS_BUCKET
      - echo "Building SAM template"
      - aws cloudformation package --template-file sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file output_sam.yaml
  post_build:
    commands:
      - echo "Build finished"

artifacts:
  files:
    - output_sam.yaml
  discard-paths: yes
