AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev
    Description: Stage that can be added to resource names

Resources:
  RDSDBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: search
      Family: aurora5.6
      Parameters:
        time_zone: US/Eastern

  RDSCluster:
    Type: "AWS::RDS::DBCluster"
    Properties:
      DatabaseName: search
      MasterUsername: search
      MasterUserPassword: search
      DBClusterParameterGroupName:
        Ref: RDSDBClusterParameterGroup

  RDSDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: search
      Family: aurora5.6
      Parameters:
        sql_mode: IGNORE_SPACE

  RDSDBInstance1:
    Type: AWS::RDS::DBInstance
    Properties:
      DBParameterGroupName:
        Ref: RDSDBParameterGroup
      Engine: aurora
      DBClusterIdentifier:
        Ref: RDSCluster
      PubliclyAccessible: true
      DBInstanceClass: db.t2.micro

  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: app/
      Runtime: nodejs4.3
      Policies: AWSLambdaBasicExecutionRole
      Events:
        ApiEventSource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: !Sub 'ApiUrl-${Stage}'